In [1]:
import numpy as np
import scipy.optimize as opt
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
np.exp(1)

2.718281828459045

In [3]:
def sigmoid(Ydash):
    return 1/(1+np.exp(-Ydash))

In [4]:
def cost(theta, X, y):
    pred = sigmoid(np.dot(X,theta.T))
    mcost = -y*np.log(pred) - (1 - y)*np.log(1-pred)
    return mcost.mean()

In [5]:
def predict(theta,X,t):
    m, n = X.shape
    p = np.zeros(shape = (m,1))
    h = sigmoid(X.dot(theta.T))
    p = 1*(h>=t)
    return p

In [6]:
data = pd.read_csv('Breast-Cancer.csv',na_values=['?'])
data.drop(['id'],1,inplace = True)
data.dropna(inplace = True)
data.head()
#data.shape

x1  x2  x3  x4  x5    x6  x7  x8  x9  label
0   5   1   1   1   2   1.0   3   1   1      2
1   5   4   4   5   7  10.0   3   2   1      2
2   3   1   1   1   2   2.0   3   1   1      2
3   6   8   8   1   3   4.0   3   7   1      2
4   4   1   1   3   2   1.0   3   1   1      2

In [7]:
X = np.array(data.values.tolist())[:,:-1]
Y_n = np.array(data.values.tolist())[:,-1]


In [8]:
num_y = []
for i in Y_n.tolist():
    if i == 2:
        num_y.append(0)
    else:
        num_y.append(1)
Y = np.array(num_y)


In [9]:
X = X.astype(np.float64)
X


array([[ 5.,  1.,  1., ...,  3.,  1.,  1.],
       [ 5.,  4.,  4., ...,  3.,  2.,  1.],
       [ 3.,  1.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 5., 10., 10., ...,  8., 10.,  2.],
       [ 4.,  8.,  6., ..., 10.,  6.,  1.],
       [ 4.,  8.,  8., ..., 10.,  4.,  1.]])

In [10]:
XX = np.append(np.ones((X.shape[0],1)),X,axis = 1)
m, n = XX.shape
XX

array([[ 1.,  5.,  1., ...,  3.,  1.,  1.],
       [ 1.,  5.,  4., ...,  3.,  2.,  1.],
       [ 1.,  3.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 1.,  5., 10., ...,  8., 10.,  2.],
       [ 1.,  4.,  8., ..., 10.,  6.,  1.],
       [ 1.,  4.,  8., ..., 10.,  4.,  1.]])

In [30]:
theta = 0.1*np.random.randn(n)
print(theta)

[ 0.11913171  0.20966166  0.10262087 -0.10058925  0.10862345  0.20545189
 -0.1832207   0.00892609  0.02728624 -0.01802443]


In [31]:
theta = opt.fmin_bfgs(cost,theta,args=(XX,Y))

Optimization terminated successfully.
         Current function value: 0.075321
         Iterations: 56
         Function evaluations: 696
         Gradient evaluations: 58


In [32]:
theta

array([-1.01043521e+01,  5.35045641e-01, -6.27391852e-03,  3.22719615e-01,
        3.30716801e-01,  9.65997747e-02,  3.83013482e-01,  4.47208146e-01,
        2.13026259e-01,  5.34832332e-01])

In [33]:
test = XX[50:75,:]
p = predict(theta,test,0.5)
print('Predict Class: ',p)
print('Accuracy: %f' % ((Y[np.where(p==Y[50:75])].size/float(Y[50:75].size))*100.0))

Predict Class:  [1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 0]
Accuracy: 96.000000
